command:
  - "streamlit"
  - "run"
  - "app.py"

env:
  - name: DATABRICKS_HOST
    value: ""
  - name: DATABRICKS_HTTP_PATH
    value: ""
  - name: DATABRICKS_CATALOG
    value: ""
  - name: DATABRICKS_SCHEMA
    value: ""
  - name: GENIE_SPACE_ID
    value: ""
  - name: DASHBOARD_EMBED_URL
    value: ""
  - name: DASHBOARD_EMBED_URL_V2
    value: ""
  - name: USE_MOCK_DATA
    value: "false"
